Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3: Verified-1
> > 
> > Build failed.
> > 
> > - rdoinfo-tripleo-master-testing-centos-8-standalone https://review.rdoproject.org/zuul/build/2f8442bc3b844f87904fc82858a3289b : SUCCESS in 1h 03m 55s (non-voting)
> > - rdoinfo-tripleo-master-testing-centos-8-scenario001-standalone https://review.rdoproject.org/zuul/build/b0c30af2d42245c6864b62157e4ef41c : FAILURE in 3h 05m 36s (non-voting)
> > - rdoinfo-tripleo-master-testing-centos-8-containers-multinode https://review.rdoproject.org/zuul/build/0276ed9d97094253a0c1550be5e617e6 : SUCCESS in 1h 20m 06s (non-voting)
> > - validate-buildsys-tags-xena-testing-puppet-scenario001-centos8 https://review.rdoproject.org/zuul/build/ec9db87eba014a139e675462f9cdc266 : FAILURE in 55m 33s
> 
> gnocchi still failed with same error in CI, local reproducer i get below with gnocchi-upgrade --config-file /etc/gnocchi/gnocchi.conf:-
> 
> 2021-07-06 09:34:10,917 [104640] ERROR    gnocchi.utils: Unable to initialize indexer driver
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/tenacity/__init__.py", line 412, in call
>     result = fn(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/gnocchi/indexer/__init__.py", line 107, in get_driver
>     split.scheme).driver
>   File "/usr/lib/python3.6/site-packages/stevedore/driver.py", line 62, in __init__
>     warn_on_missing_entrypoint=warn_on_missing_entrypoint
>   File "/usr/lib/python3.6/site-packages/stevedore/named.py", line 81, in __init__
>     verify_requirements)
>   File "/usr/lib/python3.6/site-packages/stevedore/extension.py", line 233, in _load_plugins
>     self._on_load_failure_callback(self, ep, err)
>   File "/usr/lib/python3.6/site-packages/stevedore/extension.py", line 225, in _load_plugins
>     verify_requirements,
>   File "/usr/lib/python3.6/site-packages/stevedore/named.py", line 158, in _load_one_plugin
>     verify_requirements,
>   File "/usr/lib/python3.6/site-packages/stevedore/extension.py", line 255, in _load_one_plugin
>     plugin = ep.load()
>   File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 178, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/usr/lib/python3.6/site-packages/gnocchi/indexer/sqlalchemy.py", line 46, in <module>
>     import sqlalchemy_utils
>   File "/usr/lib/python3.6/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
>     from .aggregates import aggregated  # noqa
>   File "/usr/lib/python3.6/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
>     from .functions.orm import get_column_key
>   File "/usr/lib/python3.6/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
>     from .database import (  # noqa
>   File "/usr/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 13, in <module>
>     from ..expressions import explain_analyze
>   File "/usr/lib/python3.6/site-packages/sqlalchemy_utils/expressions.py", line 4, in <module>
>     from sqlalchemy.sql.expression import (
> ImportError: cannot import name '_literal_as_text'
> 2021-07-06 09:34:11,424 [104640] ERROR    gnocchi.utils: Unable to initialize indexer driver
> 
> > - validate-buildsys-tags-xena-testing-puppet-scenario002-centos8 https://review.rdoproject.org/zuul/build/8c8b6e4a5b964e638e3501a483ac2b1e : SUCCESS in 1h 13m 26s
> > - validate-buildsys-tags-xena-testing-puppet-scenario003-centos8 https://review.rdoproject.org/zuul/build/1c49d5b2beea4127995582cfb83b9efe : SUCCESS in 1h 06m 08s
> > - validate-buildsys-tags-xena-testing-puppet-scenario004-centos8 https://review.rdoproject.org/zuul/build/f33fba7beb1b476194d90059ac386484 : SUCCESS in 46m 26s
> > - validate-buildsys-tags-xena-testing-packstack-scenario001-centos8 https://review.rdoproject.org/zuul/build/b59cd09a74034aa9a004487952c47886 : SUCCESS in 38m 20s
> > - validate-buildsys-tags-xena-testing-packstack-scenario002-centos8 https://review.rdoproject.org/zuul/build/a2f4d054e446462cb71832d7c97ce9a6 : SUCCESS in 38m 09s
> > - validate-buildsys-tags-xena-testing-packstack-scenario003-centos8 https://review.rdoproject.org/zuul/build/efccdf86347b4f5b84c22130d4346852 : FAILURE in 1h 02m 33s
> > - tox-linters https://review.rdoproject.org/zuul/build/7e164cda2c1e49f2acc78943988e6811 : SUCCESS in 5m 38s
> > - tox-py36 https://review.rdoproject.org/zuul/build/b8b7c616b6ae4b1297d826fb740054dd : SUCCESS in 5m 03s
> > - validate-dependencies-rebuilds https://review.rdoproject.org/zuul/build/c974b5585a4644e7bea9e9594c6b15d9 : SUCCESS in 5m 17s
> > - validate-buildsys-tags https://review.rdoproject.org/zuul/build/c459886b89e840be9c880a83740f31a0 : SUCCESS in 5m 05s

Would need to update sqlalchemy-utils to 0.37.8 along to clear the issue with gnocchi.

Patch-set: 3
Reviewer: Gerrit User 403 <403@270e2033-b340-4cff-9539-693957ebf0e7>