Update patch set 2
Patch Set 2:

> Patch Set 1:
> 
> > Patch Set 1: Code-Review-1
> > 
> > Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Ovn::Controller]: has no parameter named 'ovn_chassis_mac_map' (file: /etc/puppet/modules/tripleo/manifests/profile/base/neutron/agents/ovn.pp, line: 54, column: 5) on node standalone.localdomain
> > https://logserver.rdoproject.org/51/34051/1/check/rdoinfo-tripleo-victoria-release-centos-8-scenario001-standalone/e18b14e/logs/undercloud/var/log/extra/podman/containers/container-puppet-ovn_controller/stdout.log.txt.gz
> > 
> > Needs puppet-ovn release for https://review.opendev.org/c/openstack/puppet-ovn/+/782759
> 
> Proposed https://review.opendev.org/c/openstack/puppet-ovn/+/795927 and https://review.opendev.org/c/openstack/releases/+/795931

updating in testing https://review.rdoproject.org/r/c/rdoinfo/+/34080

Patch-set: 2
Reviewer: Gerrit User 403 <403@270e2033-b340-4cff-9539-693957ebf0e7>