Update patch set 1
Patch Set 1: Workflow-1

Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Nova::Compute::Pci] is already declared; cannot redeclare (file: /var/tmp/packstack/392cdf4baa4943eeb5a2032f94e30d52/modules/packstack/manifests/nova/compute.pp, line: 93) (file: /var/tmp/packstack/392cdf4baa4943eeb5a2032f94e30d52/modules/packstack/manifests/nova/compute.pp, line: 93, column: 5) 

need to adapt packstack for puppet-nova update.

Patch-set: 1
Reviewer: Gerrit User 403 <403@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Workflow=-1