puppet-pacemaker: Add the fix for property race
In order to fix LP#1688322 completely we need to bring this fix
down to newton and ocata branches.
Without this fix it, we have a race during property setup and it
will fail like this:

    May  4 13:46:44 centos-7-2-node-osic-cloud1-s3500-8719947-570244
    os-collect-config:  Error: unable to get cib
    Error: /Stage[main]/Pacemaker::Stonith/Pacemaker::Property[Disable
    STONITH]/Pcmk_property[property--stonith-enabled]: Could not evaluate:
    backup_cib: Running: /usr/sbin/pcs cluster cib
    /var/lib/pacemaker/cib/puppet-cib-backup20170504-29225-fetp7k failed
    with code: 1 ->

As Alfredo noted in the LP bug we need this in stable branches as well.

Change-Id: I06dedc81d8b0b7a8a32ddcce27dc2ac1ca020dd6